name: calculator
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  math_expressions: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets
